# Generated by Django 3.0.7 on 2024-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20240815_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
