# Generated by Django 3.0.7 on 2024-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_students_is_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='nationality',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='students',
            name='religion',
            field=models.TextField(default='Unknown'),
        ),
    ]
