# Generated by Django 3.0.7 on 2024-08-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20240817_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yearlevel_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
