# Generated by Django 3.0.7 on 2024-08-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_yearlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='yearlevel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.YearLevel'),
        ),
    ]
