# Generated by Django 3.0.7 on 2024-08-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_students_yearlevel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='course_id',
        ),
        migrations.AddField(
            model_name='subjects',
            name='yearlevel_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.YearLevel'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
