# Generated by Django 3.0.7 on 2024-08-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20240814_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='age',
        ),
        migrations.RemoveField(
            model_name='students',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='students',
            name='mobile_phone_number',
        ),
        migrations.RemoveField(
            model_name='students',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='students',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='rank_in_the_family',
        ),
        migrations.RemoveField(
            model_name='students',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='students',
            name='telephone_number',
        ),
        migrations.AlterField(
            model_name='students',
            name='nickname',
            field=models.TextField(),
        ),
    ]
