# Generated by Django 3.0.7 on 2024-08-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20240815_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session_year_id',
            new_name='session_year',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_year_id',
            new_name='session_year',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='course_id',
            new_name='course',
        ),
    ]
