# Generated by Django 3.0.7 on 2024-08-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20240817_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='session_year',
            new_name='session_year_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='session_year',
            new_name='session_year_id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='course',
            new_name='course_id',
        ),
    ]
